apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:BTgffNwiNT3GNRHWd3HKrGcO61NnoRH6CbSfUAhVdgKebk4Klj/ZPbbq/PLoyaTnvX3b2zox8cf6cxKVk4Don5wbvROPJ+XzKWWgr8tJXSnj4/juTDYDgz3OJTj922UVfl/Tg+4DiJ5GI3EnQvoMlIBjJt2zrTl7TxfzB3BKeO8r+5s94r2b3W0XZE/VH1AyEeetmij1ajovGSAs+JHdVtPyHr/Xeq2hmeHkoam7F+2e0rbBaQQ7wTEy3PaiySoflAiyW7rBbsbGH9j+EsY2590zieUvcTqBaqOdlPpyUDVkdHd0N5I5h3qXjh0=,iv:wrM90R+HqZrXcxNwpmJaSs2i9CePQHlDsmnK6bdegWE=,tag:/o8eETXsxorwBUDFhz5AXQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: audiobookshelf
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZVFWZFV6dStxdTZ1OTg1
            YmtqTmZ3NDZobndDVlI1ak8wSkhjcHhvNVFVCldKUTJ2L3Q2cDR3OUVtOUgrRmk5
            VXppanBSbHR5SmpZNWl6ZnIxZmtHSWcKLS0tIHYrOC8wV0hYQmVad3pWMzR4d216
            OWN0QWhHSHZVV3hlZ3BDUWJ3WmdxcVkKxUBpDAAjJi92WChee4Ilc2kTVnRehk/F
            Rin6LWFj1BQmKkHIeox2B1cv/kq+0jloFJM+t8kkM1MQYjw08PwJzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aq9stltdq5m9x4xcdnjdlg0jaw5udw55qhxn4rnecclfssmtaqys89un53
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T21:56:55Z"
    mac: ENC[AES256_GCM,data:8JB9blWMxCbYnrMXlzgFfQhFvz/RSjbUTkSS09u28Hl2W/5Ej2WDpnqS3zeB+P6saufykn+vaXy13YUUejJ2///WpxOpZP1F5kRNN5jMeaTIKL8Wj7+6ERjUaJFA9HJDH6OuZXU7sty7WdM/2Ki+BsB7N4Zs+3x40DstySn8NJc=,iv:KhYE5FnvBNeTFS5c0WURfJKRFpcbah6W9UvDuENywnc=,tag:dc/qdRQHbmWBIhtEMnO4Bg==,type:str]
    version: 3.13.3
