apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:i1FSQ0L0cY1HUsXV/8ugkocDbnpZQ6VultLdIT8fL0Rp1sNaKIkEPMM0ZD8BLNa8HNTi/qM/2cU=,iv:chWzu/F7za1C4snjv1NY0mEf0BxaC+8OSkbKU4xCpQ4=,tag:SxIfNbZIzfw5D0yfIlQSLA==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
    namespace: renovate
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SCtESEdwbnBHSTVub1V0
            Q244L29DSGhHanowbjltNmpzWGVWSWxVbEdVCm44SVAxUGMrMVJLQk95bm54QzMz
            N0RBYzhIRTErYXExZFhaWGdiNkFOVDgKLS0tIFJibjIwQnc3MzNYYW9RNW14R1Nt
            RlZaWWExWVNlSHNhRWgvVVN6dGNBWE0KZJbsUOpjnEnZDUUwidjGZsgWrl1CUEyu
            A/YgU9yNhedrDQ0v1QfyHG2VOxdzOzjWQBASl/xRXCJWf3GMFZY3Kg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aq9stltdq5m9x4xcdnjdlg0jaw5udw55qhxn4rnecclfssmtaqys89un53
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T07:14:35Z"
    mac: ENC[AES256_GCM,data:iMK/sJ123CajrvqC2FYlrGq1Uovt6gjnMOPBQ2XOuvJucXtBiuyU4dNL9Crd0+zxI2LYp5KWUjwfUAUVC8YSqp55uwt3cv81fK3BPbnG0bVqpC669bGrIDeJMGIC07OXyBAIZPGFP44LDiLiP9wO5zoruTbbNI/insCrYt9WBi4=,iv:88C08rUjxYbEO9nUK95XEY17kifWYxoFgkSbQ+hhhqM=,tag:tKA1/CniBeew64MtPN3EjA==,type:str]
    version: 3.13.3
